// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8n4_OAuNgxz3U2QJRZoEhElj0HF91jJE',
    appId: '1:615323948310:web:7a86d24aa1ac31a483ac37',
    messagingSenderId: '615323948310',
    projectId: 'fir-todo-app-69d28',
    authDomain: 'fir-todo-app-69d28.firebaseapp.com',
    storageBucket: 'fir-todo-app-69d28.appspot.com',
    measurementId: 'G-JTD795T69W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBulfYKBAzb7j1ptkNiSLCdJ1e5K570o5Y',
    appId: '1:615323948310:android:017c34996f32af9a83ac37',
    messagingSenderId: '615323948310',
    projectId: 'fir-todo-app-69d28',
    storageBucket: 'fir-todo-app-69d28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwXrZGBnpc8pi-OM-ouu5lKwdqGxS7XnI',
    appId: '1:615323948310:ios:898e49ee0e76720683ac37',
    messagingSenderId: '615323948310',
    projectId: 'fir-todo-app-69d28',
    storageBucket: 'fir-todo-app-69d28.appspot.com',
    iosBundleId: 'com.example.firebaseTodoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwXrZGBnpc8pi-OM-ouu5lKwdqGxS7XnI',
    appId: '1:615323948310:ios:ae9defe50d51205383ac37',
    messagingSenderId: '615323948310',
    projectId: 'fir-todo-app-69d28',
    storageBucket: 'fir-todo-app-69d28.appspot.com',
    iosBundleId: 'com.example.firebaseTodoApp.RunnerTests',
  );
}
